preset: deep-purple
jf_color_base:
  accent-1: '#507299'
  body-font: 'family=Roboto:300,500,700,400'
jf_color_menu:
  dropdown-item: ''
jf_color_s_footer:
  background: '#507299'
jf_color_s_footer_bottom:
  background: '#507299'
  text-color: 'rgba(255, 255, 255, 0.50)'
jf_color_s_header:
  background: '#507299'
jf_color_s_p_search:
  background: '#507299'
jf_cb_UC:
  accent_1: '#507299'
  menu_bg_color: '#507299'
  menu_border_color: '#ffffff'
  mobtool_bg: '#507299'
