version: 2
preset:
  image: 'gantry-admin://images/layouts/p_cta.jpg'
  name: default
  timestamp: 1439651398
layout:
  top-panel: {  }
  header: {  }
  search-panel: {  }
  left-panel: {  }
  right-panel: {  }
  overlay-panel: {  }
  /full-width-section-1/:
    -
      - jf_p_cta-6236
    -
      - jf_p_cta-8321
    -
      - jf_p_cta-1225
    -
      - jf_p_cta-2943
    -
      - jf_p_cta-8180
  /main/:
    -
      - position-position-7966
    -
      - system-messages-3370
  /full-width-section-2/: {  }
  /top-footer/: {  }
  footer: {  }
  bottom-footer: {  }
  /full-width-section-3/: {  }
structure:
  top-panel:
    type: section
    title: 'Top Panel'
    inherit:
      outline: default
      include:
        - children
        - attributes
  header:
    inherit:
      outline: default
      include:
        - children
        - attributes
  search-panel:
    type: section
    title: 'Search Panel'
    inherit:
      outline: default
      include:
        - children
        - attributes
  left-panel:
    type: section
    title: 'Left Panel'
    inherit:
      outline: default
      include:
        - attributes
        - children
  right-panel:
    type: section
    title: 'Right Panel'
    inherit:
      outline: default
      include:
        - children
        - attributes
  overlay-panel:
    type: section
    title: 'Overlay Panel'
    inherit:
      outline: default
      include:
        - children
        - attributes
  full-width-section-1:
    type: section
    title: 'Full Width Section 1'
    attributes:
      boxed: '2'
      class: ''
  main:
    attributes:
      boxed: ''
  full-width-section-2:
    type: section
    title: 'Full Width Section 2'
    attributes:
      boxed: ''
  top-footer:
    type: section
    title: 'Top Footer'
    attributes:
      boxed: ''
      class: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  bottom-footer:
    type: section
    title: 'Bottom Footer'
    inherit:
      outline: default
      include:
        - children
        - attributes
  full-width-section-3:
    type: section
    title: 'Full Width Section 3'
    attributes:
      boxed: ''
content:
  jf_p_cta-6236:
    title: 'JF Particle - CTA: Style 1 (Parallax Video)'
    attributes:
      padding: '250px 0 200px'
      textAl: center
      bg_options:
        -
          bg_type: parallax_vid
          lazyload: '1'
          maskColor: '#000000'
          maskOpacity: '0'
          scrolling: '1'
          type: cover
          bgColor: '#eeeeee'
          cover_src: ''
          parallax_src: ''
          controls: '0'
          loop: '1'
          muted: '1'
          video_type: self
          vimeo_id: ''
          youtube_id: ''
          url: images/jf/videos/
          vidname: about-us
          name: Options
      style: style_1
      style_1:
        -
          grid: '1'
          contentTextAl: center
          html: "<h1><b>Call To Action - Style 1 (Parallax Video)</b></h1>\n<a class=\"jf_venobox jf_btn jf_waves_light_40 xl fab deep-purple\" style=\"line-height:90px\" data-type=\"youtube\" href=\"http://youtu.be/Ar2wuOxBpDw\"><i class=\"material-icons\">play_arrow</i></a>"
          name: 'Item 1'
  jf_p_cta-8321:
    title: 'JF Particle - CTA: Style 1 (Parallax Image)'
    attributes:
      contentW: default
      padding: '170px 0'
      bg_options:
        -
          bg_type: parallax_img
          lazyload: '1'
          bgColor: '#eeeeee'
          cover_src: ''
          maskColor: '#000000'
          maskOpacity: '30'
          scrolling: '0'
          parallax_src: 'gantry-media://jf/elements/parallax/screen_1.jpg'
          type: default
          url: images/jf/videos/
          vidname: dreamscapes
          controls: '1'
          loop: '1'
          muted: '1'
          name: Options
      style_1:
        -
          grid: '1'
          contentTextAl: left
          contentTheme: light
          html: "<h1 data-animation=\"fadeInLeftShort\" data-animation-type=\"onview\" data-animation-delay=\"0.5\"><b>Call To Action - Style 1 (Parallax Image)</b></h1>\n<button class=\"jf_btn jf_waves_light_40 xl raised deep-purple\" style=\"text-transform:capitalize;letter-spacing:1px\" data-animation=\"fadeInLeftShort\" data-animation-type=\"onview\" data-animation-delay=\"1\">Learn More</button>"
          name: 'Item 1'
  jf_p_cta-1225:
    title: 'JF Particle - CTA: Style 1 (Background Color)'
    attributes:
      contentW: default
      padding: '100px 0'
      bg_options:
        -
          bg_type: color
          lazyload: '1'
          bgColor: '#673ab7'
          cover_src: ''
          maskColor: '#000000'
          maskOpacity: '10'
          scrolling: '1'
          parallax_src: ''
          type: default
          url: images/jf/videos/
          vidname: dreamscapes
          controls: '1'
          loop: '1'
          muted: '1'
          name: Options
      style_1:
        -
          grid: 2-3
          contentTextAl: left
          contentTheme: light
          html: "<h1 style=\"color:#fff;font-weight:700\" data-animation=\"fadeInLeftShort\" data-animation-type=\"onview\" data-animation-delay=\"0.5\">Call To Action - Style 1 (Background Color)</h1>\n<p style=\"color:#fff;font-size:20px\" data-animation=\"fadeInLeftShort\" data-animation-type=\"onview\" data-animation-delay=\"1\">Mid et quis hac scelerisque ut, purus ut risus lacus turpis duis lectus risus mattis nascetur tincidunt dis.</p>"
          css3_anim_name: ''
          css3_anim_type: onview
          css3_anim_delay: ''
          name: 'Left Column'
        -
          grid: 1-3
          contentTextAl: right
          contentTheme: light
          html: '<button class="jf_btn jf_waves_dark_20 xl raised yellow" style="text-transform:capitalize;letter-spacing:1px;margin:20px 0 0 0" data-animation="fadeInRightShort" data-animation-type="onview" data-animation-delay="1.5">SIGN UP</button>'
          css3_anim_name: ''
          css3_anim_type: onview
          css3_anim_delay: ''
          name: 'Right Column'
  jf_p_cta-2943:
    title: "JF Particle - CTA:\_Style 2 (Left-Side Content With Right-Side Image)"
    attributes:
      padding: '0'
      bg_options:
        -
          bg_type: color
          lazyload: '1'
          bgColor: '#eeeeee'
          cover_src: ''
          maskColor: '#000000'
          maskOpacity: '10'
          scrolling: '1'
          parallax_src: ''
          type: default
          url: images/jf/videos/
          vidname: dreamscapes
          controls: '1'
          loop: '1'
          muted: '1'
          name: Options
      style: style_2
      style_2:
        -
          grid: 1-2
          contentTextAl: left
          padding: 50px
          contentStyle: html
          contentTheme: light
          html: "<h1 style=\"font-weight:500;margin:80px 0 0\" data-animation=\"fadeInLeftShort\" data-animation-type=\"onview\" data-animation-delay=\"0.5\">CTA: Style 2 (Right Image)</h1>\n<p data-animation=\"fadeInLeftShort\" data-animation-type=\"onview\" data-animation-delay=\"1\">Magna pulvinar enim mid vel? Egestas aliquam cras augue turpis et! Ultricies diam elit. Magna nunc.</p>\n<button class=\"jf_btn jf_waves_light_40 l raised deep-purple\" data-animation=\"fadeInLeftShort\" data-animation-type=\"onview\" data-animation-delay=\"1.5\">Read More</button>\n"
          image_src: ''
          image_alt: ''
          css3_anim_name: ''
          css3_anim_type: onview
          css3_anim_delay: ''
          name: 'Left Column'
        -
          grid: 1-2
          contentTextAl: left
          padding: '0'
          contentStyle: image
          contentTheme: light
          html: ''
          image_src: 'gantry-media://jf/elements/parallax/screen_2.jpg'
          image_alt: ''
          image_lazyload: '1'
          image_lazyload_src: 'gantry-media://jf/blank.gif'
          css3_anim_name: fadeInRightShort
          css3_anim_type: onview
          css3_anim_delay: '1'
          name: 'Right Column'
  jf_p_cta-8180:
    title: "JF Particle - CTA:\_Style 2 (Left-Side Image With Right-Side Content)"
    attributes:
      padding: '0'
      bg_options:
        -
          bg_type: color
          lazyload: '1'
          bgColor: '#ffffff'
          cover_src: ''
          maskColor: '#000000'
          maskOpacity: '10'
          scrolling: '1'
          parallax_src: ''
          type: default
          url: images/jf/videos/
          vidname: dreamscapes
          controls: '1'
          loop: '1'
          muted: '1'
          name: Options
      style: style_2
      style_2:
        -
          grid: 1-2
          contentTextAl: center
          padding: '100px 50px'
          contentStyle: image
          contentTheme: light
          html: ''
          image_src: 'gantry-media://jf/particles/ctabs/1.png'
          image_alt: ''
          image_lazyload: '1'
          image_lazyload_src: 'gantry-media://jf/blank.gif'
          css3_anim_name: fadeInLeftShort
          css3_anim_type: onview
          css3_anim_delay: '0.5'
          name: 'Left Column'
        -
          grid: 1-2
          contentTextAl: left
          padding: 50px
          contentStyle: html
          contentTheme: light
          html: "<h1 style=\"font-weight:500;margin:50px 0 20px\" data-animation=\"zoomIn\" data-animation-type=\"onview\" data-animation-delay=\"0.5\">CTA: Style 2 (Left Image)</h1>\n<div class=\"jf_icon_box leftfloat animate_icon\" style=\"padding:10px 0;margin:0\" data-animation=\"zoomIn\" data-animation-type=\"onview\" data-animation-delay=\"0.8\">\n\t<div class=\"icon\"><img src=\"images/jf/elements/icon_boxes/fantasy.svg\" alt=\"\"></div>\n\t<h3 class=\"header\">Easy Install</h3>\n\t<div class=\"descr\" style=\"font-size:16px\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae justo est.</div>\n</div>\n<div class=\"jf_icon_box leftfloat animate_icon\" style=\"padding:10px 0;margin:0\" data-animation=\"zoomIn\" data-animation-type=\"onview\" data-animation-delay=\"1.1\">\n\t<div class=\"icon\"><img src=\"images/jf/elements/icon_boxes/novel.svg\" alt=\"\"></div>\n\t<h3 class=\"header\">Multi-Purpose</h3>\n\t<div class=\"descr\" style=\"font-size:16px\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae justo est.</div>\n</div>"
          image_src: ''
          image_alt: ''
          css3_anim_name: ''
          css3_anim_type: onview
          css3_anim_delay: ''
          name: 'Right Column'
  position-position-7966:
    title: 'Module Position'
    inherit:
      outline: default
      particle: position-position-2694
      include:
        - block
        - attributes
  system-messages-3370:
    inherit:
      outline: default
      particle: system-messages-1489
      include:
        - attributes
        - block
