name: 30
timestamp: 1474297176
version: 7
preset:
  image: 'gantry-admin://images/layouts/page_portfolio.jpg'
  name: default
  timestamp: 1439651398
positions:
  breadcrumbs: Breadcrumbs
  right-panel: 'Module Position'
  footer: Footer
sections:
  top-panel: 'Top Panel'
  search-panel: 'Search Panel'
  left-panel: 'Left Panel'
  right-panel: 'Right Panel'
  overlay-panel: 'Overlay Panel'
  full-width-section-1: 'Full Width Section 1'
  full-width-section-2: 'Full Width Section 2'
  top-footer: 'Top Footer'
  bottom-footer: 'Bottom Footer'
  full-width-section-3: 'Full Width Section 3'
  header: Header
  main: Main
  footer: Footer
particles:
  jf_p_cta:
    jf_p_cta-7008: 'JF Particle - CTA'
  position:
    position-position-9971: Breadcrumbs
    position-position-8817: 'Module Position'
    position-position-1165: Footer
  jf_p_portfolio:
    jf_p_portfolio-9883: 'JF Particle - Portfolio - Style 1'
  messages:
    system-messages-7706: 'System Messages'
  custom:
    custom-6602: 'Custom HTML'
    custom-6827: 'Custom HTML'
    custom-2616: 'Custom HTML'
    custom-8529: 'Custom HTML'
  logo:
    logo-2145: Logo
    logo-6492: Logo
    logo-3103: Logo
  menu:
    menu-9589: Menu
  jf_panel_buttons:
    jf_panel_buttons-7978: 'JF Panel Buttons'
  module:
    position-module-8988: 'Module Instance'
    position-module-4691: 'Module Instance'
    position-module-5239: 'Module Instance'
    position-module-1322: 'Module Instance'
    position-module-9497: 'Module Instance'
    position-module-5684: 'Module Instance'
    position-module-4149: 'Module Instance'
    position-module-7026: 'Module Instance'
  jf_switcher:
    jf_switcher-6942: 'JF Style Switcher'
  copyright:
    copyright-2731: Copyright
inherit:
  default:
    top-panel: top-panel
    header: header
    search-panel: search-panel
    left-panel: left-panel
    right-panel: right-panel
    overlay-panel: overlay-panel
    system-messages-7706: system-messages-1489
    footer: footer
    bottom-footer: bottom-footer
    custom-6602: custom-3485
    custom-6827: custom-1392
    logo-2145: logo-5705
    menu-9589: menu-2947
    jf_panel_buttons-7978: jf_panel_buttons-3313
    position-module-8988: position-module-1605
    position-module-4691: position-module-6496
    position-module-5239: position-module-1290
    position-module-1322: position-module-3392
    position-module-9497: position-module-7385
    position-module-5684: position-module-2571
    position-position-8817: position-position-5361
    jf_switcher-6942: jf_switcher-6426
    position-position-1165: position-position-9915
    logo-6492: logo-2653
    custom-2616: custom-5362
    position-module-4149: position-module-3742
    custom-8529: custom-4368
    copyright-2731: copyright-3966
    logo-3103: logo-9507
    position-module-7026: position-module-4901
