name: '10'
timestamp: 1490269272
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1490269272
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-4730: 'Logo / Image'
    logo-3568: 'Logo / Image'
  menu:
    menu-7488: Menu
  social:
    social-1491: Social
  position:
    position-position-6393: Aside
    position-position-2967: Sidebar
  content:
    system-content-3450: 'Page Content'
  copyright:
    copyright-3837: Copyright
  horizontalmenu:
    horizontalmenu-5015: 'Horizontal Menu'
  totop:
    totop-4669: 'To Top'
  mobile-menu:
    mobile-menu-6250: Mobile-menu
inherit:
  default:
    navigation: navigation
    logo-9608: logo-9608
    menu-6409: menu-6409
    social-3171: social-3171
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    position-position-4734: position-position-4734
    mainbar: mainbar
    system-content-1587: system-content-1587
    sidebar: sidebar
    position-position-3949: position-position-3949
    footer: footer
    logo-9571: logo-9571
    copyright-1736: copyright-1736
    horizontalmenu-9034: horizontalmenu-9034
    totop-8670: totop-8670
    offcanvas: offcanvas
    mobile-menu-5697: mobile-menu-5697
    logo-4730: logo-9608
    menu-7488: menu-6409
    social-1491: social-3171
    position-position-6393: position-position-4734
    system-content-3450: system-content-1587
    position-position-2967: position-position-3949
    logo-3568: logo-9571
    copyright-3837: copyright-1736
    horizontalmenu-5015: horizontalmenu-9034
    totop-4669: totop-8670
    mobile-menu-6250: mobile-menu-5697
