name: '9'
timestamp: 1490268331
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.jpg'
  name: default
  timestamp: 1490205216
positions:
  right-panel: 'Module Position'
  breadcrumbs: Breadcrumbs
  right-sidebar: 'Module Position'
  footer: Footer
sections:
  top-panel: 'Top Panel'
  search-panel: 'Search Panel'
  left-panel: 'Left Panel'
  right-panel: 'Right Panel'
  overlay-panel: 'Overlay Panel'
  full-width-section-1: 'Full Width Section 1'
  full-width-section-2: 'Full Width Section 2'
  top-footer: 'Top Footer'
  bottom-footer: 'Bottom Footer'
  full-width-section-3: 'Full Width Section 3'
  header: Header
  main: Main
  footer: Footer
particles:
  custom:
    custom-3485: 'Custom HTML'
    custom-1392: 'Custom HTML'
    custom-5362: 'Custom HTML'
    custom-4368: 'Custom HTML'
  module:
    position-module-2491: 'Eng-Ru Default home'
    position-module-1605: 'Module Instance'
    position-module-6496: 'Module Instance'
    position-module-1290: 'Module Instance'
    position-module-3392: 'Module Instance'
    position-module-7385: 'Module Instance'
    position-module-2571: 'Module Instance'
    position-module-3742: 'Module Instance'
    position-module-4901: 'Module Instance'
  jf_panel_buttons:
    jf_panel_buttons-3313: 'JF Panel Buttons'
  position:
    position-position-5361: 'Module Position'
    position-position-2694: Breadcrumbs
    position-position-8845: 'Module Position'
    position-position-9915: Footer
  jf_switcher:
    jf_switcher-6426: 'JF Style Switcher'
  messages:
    system-messages-1489: 'System Messages'
  content:
    system-content-5204: 'Page Content'
  logo:
    logo-2653: Logo
    logo-9507: Logo
  copyright:
    copyright-3966: Copyright
inherit: {  }
