name: _offline
timestamp: 1490269327
version: 7
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1490269327
positions:
  footer: Footer
sections:
  header: Header
  main: Main
  footer: Footer
particles:
  logo:
    logo-1384: Logo
  spacer:
    spacer-3174: Spacer
    spacer-8372: Spacer
  messages:
    system-messages-9007: 'System Messages'
  content:
    system-content-6128: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-6795: Copyright
  branding:
    branding-5080: Branding
inherit: {  }
