name: 32
timestamp: 1474297176
version: 7
preset:
  image: 'gantry-admin://images/layouts/page_faq.jpg'
  name: default
  timestamp: 1439651398
positions:
  breadcrumbs: Breadcrumbs
  right-sidebar: 'Module Position'
  right-panel: 'Module Position'
  footer: Footer
sections:
  top-panel: 'Top Panel'
  search-panel: 'Search Panel'
  left-panel: 'Left Panel'
  right-panel: 'Right Panel'
  overlay-panel: 'Overlay Panel'
  full-width-section-1: 'Full Width Section 1'
  full-width-section-2: 'Full Width Section 2'
  top-footer: 'Top Footer'
  bottom-footer: 'Bottom Footer'
  full-width-section-3: 'Full Width Section 3'
  header: Header
  main: Main
  footer: Footer
particles:
  jf_p_cta:
    jf_p_cta-5861: 'JF Particle - CTA'
  position:
    position-position-4869: Breadcrumbs
    position-position-7688: 'Module Position'
    position-position-2532: 'Module Position'
    position-position-3467: Footer
  messages:
    system-messages-8912: 'System Messages'
  jf_p_tabs:
    jf_p_tabs-7420: 'JF Particle - Container Tabs'
  custom:
    custom-8417: 'Custom HTML'
    custom-9031: 'Custom HTML'
    custom-7074: 'Custom HTML'
    custom-5445: 'Custom HTML'
    custom-8547: 'Custom HTML'
    custom-7241: 'Custom HTML'
  spacer:
    spacer-5611: Spacer
    spacer-3212: Spacer
  logo:
    logo-8118: Logo
    logo-8976: Logo
    logo-3362: Logo
  menu:
    menu-7834: Menu
  jf_panel_buttons:
    jf_panel_buttons-6520: 'JF Panel Buttons'
  module:
    position-module-3491: 'Module Instance'
    position-module-4750: 'Module Instance'
    position-module-2816: 'Module Instance'
    position-module-4569: 'Module Instance'
    position-module-2964: 'Module Instance'
    position-module-8241: 'Module Instance'
    position-module-2676: 'Module Instance'
    position-module-2994: 'Module Instance'
  jf_switcher:
    jf_switcher-1809: 'JF Style Switcher'
  copyright:
    copyright-7389: Copyright
inherit:
  default:
    top-panel: top-panel
    header: header
    search-panel: search-panel
    left-panel: left-panel
    right-panel: right-panel
    overlay-panel: overlay-panel
    system-messages-8912: system-messages-1489
    position-position-7688: position-position-8845
    footer: footer
    bottom-footer: bottom-footer
    custom-7074: custom-3485
    custom-5445: custom-1392
    logo-8118: logo-5705
    menu-7834: menu-2947
    jf_panel_buttons-6520: jf_panel_buttons-3313
    position-module-3491: position-module-1605
    position-module-4750: position-module-6496
    position-module-2816: position-module-1290
    position-module-4569: position-module-3392
    position-module-2964: position-module-7385
    position-module-8241: position-module-2571
    position-position-2532: position-position-5361
    jf_switcher-1809: jf_switcher-6426
    position-position-3467: position-position-9915
    logo-8976: logo-2653
    custom-8547: custom-5362
    position-module-2676: position-module-3742
    custom-7241: custom-4368
    copyright-7389: copyright-3966
    logo-3362: logo-9507
    position-module-2994: position-module-4901
