name: _body_only
timestamp: 1490269327
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1490269327
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-4779: 'System Messages'
  content:
    system-content-5100: 'Page Content'
inherit: {  }
