name: _body_only
timestamp: 1490210431
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1452207504
positions: {  }
sections:
  main: Main
particles:
  menu:
    menu-7032: Menu
  messages:
    system-messages-9397: 'System Messages'
  content:
    system-content-3526: 'Page Content'
inherit: {  }
