version: 2
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1452207504
layout:
  /main/:
    -
      - 'menu-7032 50'
      - 'system-messages-9397 50'
    -
      - system-content-3526
structure:
  main:
    attributes:
      boxed: ''
content:
  menu-7032:
    attributes:
      menu: testa
