name: 25
timestamp: 1474297178
version: 7
preset:
  image: 'gantry-admin://images/layouts/p_testimon.jpg'
  name: default
  timestamp: 1439651398
positions:
  breadcrumbs: Breadcrumbs
  right-panel: 'Module Position'
  footer: Footer
sections:
  top-panel: 'Top Panel'
  search-panel: 'Search Panel'
  left-panel: 'Left Panel'
  right-panel: 'Right Panel'
  overlay-panel: 'Overlay Panel'
  full-width-section-1: 'Full Width Section 1'
  full-width-section-2: 'Full Width Section 2'
  top-footer: 'Top Footer'
  bottom-footer: 'Bottom Footer'
  full-width-section-3: 'Full Width Section 3'
  header: Header
  main: Main
  footer: Footer
particles:
  jf_p_testimonials:
    jf_p_testimonials-5468: 'JF Particle - Testimonials - Style 2 (White, Shadow)'
    jf_p_testimonials-7698: 'JF Particle - Testimonials - Style 2'
    jf_p_testimonials-4350: 'JF Particle - Testimonials - Style 1 (Dark, 1 Item)'
    jf_p_testimonials-5053: 'JF Particle - Testimonials - Style 1'
    jf_p_testimonials-2050: 'JF Particle - Testimonials - Style 2 (Left Floated)'
    jf_p_testimonials-8943: 'JF Particle - Testimonials - Style 2 (Right Floated)'
  position:
    position-position-8025: Breadcrumbs
    position-position-6225: 'Module Position'
    position-position-2774: Footer
  messages:
    system-messages-3090: 'System Messages'
  custom:
    custom-1165: 'Custom HTML'
    custom-5035: 'Custom HTML'
    custom-5283: 'Custom HTML'
    custom-1793: 'Custom HTML'
  logo:
    logo-7383: Logo
    logo-6879: Logo
    logo-3966: Logo
  menu:
    menu-8047: Menu
  jf_panel_buttons:
    jf_panel_buttons-7141: 'JF Panel Buttons'
  module:
    position-module-6996: 'Module Instance'
    position-module-1895: 'Module Instance'
    position-module-2535: 'Module Instance'
    position-module-6427: 'Module Instance'
    position-module-5059: 'Module Instance'
    position-module-7447: 'Module Instance'
    position-module-1612: 'Module Instance'
    position-module-7996: 'Module Instance'
  jf_switcher:
    jf_switcher-5825: 'JF Style Switcher'
  copyright:
    copyright-4532: Copyright
inherit:
  default:
    top-panel: top-panel
    header: header
    search-panel: search-panel
    left-panel: left-panel
    right-panel: right-panel
    overlay-panel: overlay-panel
    position-position-8025: position-position-2694
    system-messages-3090: system-messages-1489
    footer: footer
    bottom-footer: bottom-footer
    custom-1165: custom-3485
    custom-5035: custom-1392
    logo-7383: logo-5705
    menu-8047: menu-2947
    jf_panel_buttons-7141: jf_panel_buttons-3313
    position-module-6996: position-module-1605
    position-module-1895: position-module-6496
    position-module-2535: position-module-1290
    position-module-6427: position-module-3392
    position-module-5059: position-module-7385
    position-module-7447: position-module-2571
    position-position-6225: position-position-5361
    jf_switcher-5825: jf_switcher-6426
    position-position-2774: position-position-9915
    logo-6879: logo-2653
    custom-5283: custom-5362
    position-module-1612: position-module-3742
    custom-1793: custom-4368
    copyright-4532: copyright-3966
    logo-3966: logo-9507
    position-module-7996: position-module-4901
