atoms:
  -
    type: jf_features
    title: 'JF Features'
    attributes:
      enabled: '1'
      modernizr: '1'
      jQueryEasing: '1'
      jf_iewarning: '1'
      jf_smoothScroll: '1'
      jf_lazyload: '1'
      stickyHeader:
        - { enable: '1', slideup: '1', menu_padding: 1.4rem, logo_size: 68px, logo_scale: '0.28', homepage: transparent, name: Options }
      jf_styleSwitcher: '1'
      jf_preloader:
        - { enable: '1', bgColor: '#f5f5f5', name: Options }
      jf_scrollTop:
        - { enable: '1', class: jf_waves_dark_10, bgColor: '#ffeb3b', iconColor: '#222222', name: Options }
      jf_syntax:
        - { prism: '0', typo_preview: '0', name: Options }
  -
    type: jf_elements
    title: 'JF Elements'
    attributes:
      enabled: '1'
      typo: '1'
      waves:
        - { enable: '1', duration: '500', delay: '200', dark10: '.jf_mm_pro_wrapper li a,#g-main .nav.menu a,.search button[name="Search"],.platform-content .registration a.btn,.platform-content .profile .btn,.platform-content .profile-edit a.btn,.dropdown-menu li a,.readmore a,.tags a,#g-main .jf_sp_nf_item,.carousel-control', dark20: '.g-main-nav .g-sublevel > li .g-menu-item-container,div.jf_select li,#g-left-panel .jf_close,#g-right-panel .jf_close,.pagination a,.jf_cb_btn.raised.default,.cbLogoutForm .jf_cblogin_profilemenu li a,.cbLogoutForm .jf_cblogin_profilemenu li button,#uddeim #uddeim-navbar2 ul li a,#uddeim #uddeim-navbar2 ul li span,.jf_cb_mt_c_menu li a', dark30: '', dark40: '', dark50: '', dark60: '', dark70: '', dark80: '', dark90: '', dark100: '', light10: '#g-bottom-footer .nav > li > a,#g-footer .nav > li > a,.g-main-nav .g-toplevel > li > .g-menu-item-container,.jf_panel_btn,#g-footer .jf_linkhover', light20: '.jf_mm_pro_panelBtn,#g-search-panel .jf_sp_nf_item,#Kunena #ktop ul.menu li a,.jf_ku_pos_panelBtn,.jf_cb_mobtool ul li', light30: '', light40: '#finder-search .btn,.platform-content .registration .btn-primary,.platform-content .login .btn-primary,.platform-content .remind .btn-primary,.platform-content .contact .btn-primary,.platform-content .reset .btn-primary,.platform-content .profile-edit .btn-primary,.blog-featured .item-image a,.blog .item-image a,.icons .dropdown-toggle,.pagenav a,.jf_cb_btn.raised.accent', light50: '', light60: '', light70: '', light80: '', light90: '', light100: '', shadowDark10: '', shadowDark20: '', shadowDark30: '', shadowDark40: '', shadowDark50: '', shadowDark60: '', shadowDark70: '', shadowDark80: '', shadowDark90: '', shadowDark100: '', shadowLight10: '', shadowLight20: '', shadowLight30: '', shadowLight40: '', shadowLight50: '', shadowLight60: '', shadowLight70: '', shadowLight80: '', shadowLight90: '', shadowLight100: '', name: Options }
      buttons: '1'
      tabs: '1'
      acc_toggl: '0'
      dropdowns: '1'
      dialogs: '0'
      pricing: '0'
      cards: '1'
      messages: '0'
      social_icons: '1'
      tooltips: '0'
      bs_buttons: '0'
      bs_modals: '0'
      bs_dropdowns: '0'
      bs_popovers: '1'
      bs_carousels: '0'
      cssAnim:
        - { enable: '1', all_anim: '0', all_anim_sheet: //cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.0/animate.min.css, custom_anim: '1', css3_animate_1_type: '', css3_animate_1_delay: '', css3_animate_1_tags: '', css3_animate_2_type: '', css3_animate_2_delay: '', css3_animate_2_tags: '', css3_animate_3_type: '', css3_animate_3_delay: '', css3_animate_3_tags: '', css3_animate_4_type: '', css3_animate_4_delay: '', css3_animate_4_tags: '', css3_animate_5_type: '', css3_animate_5_delay: '', css3_animate_5_tags: '', css3_animate_6_type: '', css3_animate_6_delay: '', css3_animate_6_tags: '', css3_animate_7_type: '', css3_animate_7_delay: '', css3_animate_7_tags: '', name: Options }
      flip_boxes: '0'
      parallaxSections:
        - { enable: '1', videobg_self: '1', custom_par_1_id: '#g-footer', custom_par_1_wrap: '0', custom_par_1_image: 'gantry-media://map.png', custom_par_1_type: contain, custom_par_1_maskColor: '#000000', custom_par_1_maskOpacity: '0', custom_par_2_id: '', custom_par_2_wrap: '0', custom_par_2_image: '', custom_par_2_type: cover, custom_par_2_maskColor: '#000000', custom_par_2_maskOpacity: '10', custom_par_3_id: '', custom_par_3_wrap: '0', custom_par_3_image: '', custom_par_3_type: cover, custom_par_3_maskColor: '#000000', custom_par_3_maskOpacity: '10', custom_par_4_id: '', custom_par_4_wrap: '0', custom_par_4_image: '', custom_par_4_type: cover, custom_par_4_maskColor: '#000000', custom_par_4_maskOpacity: '10', custom_par_5_id: '', custom_par_5_wrap: '0', custom_par_5_image: '', custom_par_5_type: cover, custom_par_5_maskColor: '#000000', custom_par_5_maskOpacity: '10', custom_par_6_id: '', custom_par_6_wrap: '0', custom_par_6_image: '', custom_par_6_type: cover, custom_par_6_maskColor: '#000000', custom_par_6_maskOpacity: '10', custom_par_7_id: '', custom_par_7_wrap: '0', custom_par_7_image: '', custom_par_7_type: cover, custom_par_7_maskColor: '#000000', custom_par_7_maskOpacity: '10', custom_par_8_id: '', custom_par_8_wrap: '0', custom_par_8_image: '', custom_par_8_type: cover, custom_par_8_maskColor: '#000000', custom_par_8_maskOpacity: '10', custom_par_9_id: '', custom_par_9_wrap: '0', custom_par_9_image: '', custom_par_9_type: cover, custom_par_9_maskColor: '#000000', custom_par_9_maskOpacity: '10', name: Options }
      lightboxes:
        - { enable_photoswipe: '1', ps_caption: '1', ps_fullscreen: '1', ps_zoom: '1', ps_share: '1', ps_counter: '1', ps_arrow: '1', ps_preloader: '1', enable_venobox: '0', vb_numeration: '1', vb_infinite: '1', name: Options }
      img_hovers: '1'
      hotspots: '0'
      carousels: '1'
      testimonials: '1'
      iconLists:
        - { enable: '1', url_1: //netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css, url_2: '//fonts.googleapis.com/icon?family=Material+Icons', url_3: '', name: Options }
      icon_boxes: '1'
      counters: '1'
      progress_bars: '0'
      process_steps: '0'
      pies_inf: '0'
      charts: '0'
      graphs: '0'
