name: _error
timestamp: 1490269327
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1490269327
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-5915: Logo
  spacer:
    spacer-8271: Spacer
    spacer-7882: Spacer
  menu:
    menu-7205: Menu
  content:
    system-content-1649: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-6245: Copyright
  branding:
    branding-1756: Branding
  mobile-menu:
    mobile-menu-6737: Mobile-menu
inherit: {  }
