name: 19
timestamp: 1474297176
version: 7
preset:
  image: 'gantry-admin://images/layouts/page_about.jpg'
  name: default
  timestamp: 1439651398
positions:
  breadcrumbs: Breadcrumbs
  right-panel: 'Module Position'
  footer: Footer
sections:
  top-panel: 'Top Panel'
  search-panel: 'Search Panel'
  left-panel: 'Left Panel'
  right-panel: 'Right Panel'
  overlay-panel: 'Overlay Panel'
  full-width-section-1: 'Full Width Section 1'
  full-width-section-2: 'Full Width Section 2'
  top-footer: 'Top Footer'
  bottom-footer: 'Bottom Footer'
  full-width-section-3: 'Full Width Section 3'
  header: Header
  main: Main
  footer: Footer
particles:
  jf_p_cta:
    jf_p_cta-2175: 'JF Particle - CTA'
    jf_p_cta-8128: 'JF Particle - CTA'
  position:
    position-position-7094: Breadcrumbs
    position-position-9873: 'Module Position'
    position-position-5234: Footer
  jf_p_ft_intro:
    jf_p_ft_intro-5463: 'JF Particle - Features Intro'
  jf_p_stat:
    jf_p_stat-7597: 'JF Particle - Statistics - Style 1 (Counter)'
    jf_p_stat-3824: "JF Particle - Statistics\_- Style 2 (Progress Bar)"
  jf_p_teams:
    jf_p_teams-2946: 'JF Particle - Teams - Style 1 (Boxed)'
  jf_p_clients:
    jf_p_clients-9670: 'JF Particle - Clients - Style 2 (Dark, Bordered)'
  jf_p_testimonials:
    jf_p_testimonials-7379: 'JF Particle - Testimonials - Style 2 (White, Shadow)'
  messages:
    system-messages-2227: 'System Messages'
  custom:
    custom-3453: 'Custom HTML'
    custom-3260: 'Custom HTML'
    custom-6111: 'Custom HTML'
    custom-7826: 'Custom HTML'
  logo:
    logo-5698: Logo
    logo-6578: Logo
    logo-5424: Logo
  menu:
    menu-5253: Menu
  jf_panel_buttons:
    jf_panel_buttons-1523: 'JF Panel Buttons'
  module:
    position-module-2670: 'Module Instance'
    position-module-4955: 'Module Instance'
    position-module-3494: 'Module Instance'
    position-module-3864: 'Module Instance'
    position-module-8672: 'Module Instance'
    position-module-2717: 'Module Instance'
    position-module-2236: 'Module Instance'
    position-module-4454: 'Module Instance'
  jf_switcher:
    jf_switcher-2321: 'JF Style Switcher'
  copyright:
    copyright-1633: Copyright
inherit:
  default:
    top-panel: top-panel
    header: header
    search-panel: search-panel
    left-panel: left-panel
    right-panel: right-panel
    overlay-panel: overlay-panel
    system-messages-2227: system-messages-1489
    footer: footer
    bottom-footer: bottom-footer
    custom-3453: custom-3485
    custom-3260: custom-1392
    logo-5698: logo-5705
    menu-5253: menu-2947
    jf_panel_buttons-1523: jf_panel_buttons-3313
    position-module-2670: position-module-1605
    position-module-4955: position-module-6496
    position-module-3494: position-module-1290
    position-module-3864: position-module-3392
    position-module-8672: position-module-7385
    position-module-2717: position-module-2571
    position-position-9873: position-position-5361
    jf_switcher-2321: jf_switcher-6426
    position-position-5234: position-position-9915
    logo-6578: logo-2653
    custom-6111: custom-5362
    position-module-2236: position-module-3742
    custom-7826: custom-4368
    copyright-1633: copyright-3966
    logo-5424: logo-9507
    position-module-4454: position-module-4901
