name: 13
timestamp: 1490269327
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1490269327
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-5578: Menu
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-5124: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-4408: Copyright
  social:
    social-5168: Social
  branding:
    branding-3367: Branding
  mobile-menu:
    mobile-menu-5272: 'Mobile Menu'
inherit: {  }
