name: '14'
timestamp: 1556792571
version: 7
preset:
  image: 'gantry-admin://images/layouts/3-col.png'
  name: 3_column
  timestamp: 1490269327
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  sidebar: Sidebar
  aside: Aside
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  module:
    position-module-9827: LOgo_3_top
    position-module-7987: 'Menu hone en-ru'
    position-module-6278: Stop_zindex
    position-module-4844: 'Module Instance'
    position-module-5086: 'Новости к-2 Руская версия'
    position-module-3231: 'News eng version K-2'
  position:
    position-footer: Footer
  copyright:
    copyright-2657: Copyright
  custom:
    custom-7331: 'Custom HTML'
  mobile-menu:
    mobile-menu-3879: Mobile-menu
inherit: {  }
