version: 2
preset:
  image: 'gantry-admin://images/layouts/3-col.png'
  name: 3_column
  timestamp: 1490269327
layout:
  /header/:
    -
      - position-module-9827
    -
      - position-module-7987
  /navigation/:
    -
      - position-module-6278
  /container-main/:
    -
      -
        'sidebar 16': {  }
      -
        'main 58':
          -
            - position-module-4844
          -
            - position-module-5086
          -
            - position-module-3231
      -
        'aside 26': {  }
  /footer/:
    -
      - position-footer
    -
      - 'copyright-2657 20'
      - 'custom-7331 80'
  offcanvas:
    -
      - mobile-menu-3879
structure:
  header:
    attributes:
      boxed: '2'
      class: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
    subtype: aside
    block:
      fixed: 1
  aside:
    block:
      fixed: 1
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-module-9827:
    title: LOgo_3_top
    attributes:
      module_id: '118'
      key: logo_3_top
  position-module-7987:
    title: 'Menu hone en-ru'
    attributes:
      module_id: '96'
      key: menu-hone-en-ru
  position-module-6278:
    title: Stop_zindex
    attributes:
      module_id: '119'
      key: stop_zindex
  position-module-4844:
    title: 'Module Instance'
    attributes:
      module_id: '121'
  position-module-5086:
    title: 'Новости к-2 Руская версия'
    attributes:
      enabled: 0
      module_id: '113'
  position-module-3231:
    title: 'News eng version K-2'
    attributes:
      enabled: 0
      module_id: '114'
  position-footer:
    attributes:
      key: footer
  copyright-2657:
    attributes:
      date:
        start: 'SHEXP 2016'
        end: '2019'
      owner: ''
  custom-7331:
    title: 'Custom HTML'
    attributes:
      html: "<div>\n<a> Education, Audiovisual and Culture Executive Agency\n<br> Call for proposals EAC/A04/2015 - Jean Monnet Activities\n<br><span style=\"color: #015175;\"> Agreement n. 2016 - 2594/001-001\nProject № 575018-EPP-1-2016-1-RU-EPPJMO-MODULE\n<div>\n<p>The European Commission support for the production of this publication does not constitute an endorsement of the contents which reflects the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein.</p>"
