version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.jpg'
  name: _offline
  timestamp: 1440196745
layout:
  /top-panel/: {  }
  /header/:
    -
      - 'logo-2843 33.3'
      - 'custom-3381 33.3'
      - 'jf_panel_buttons-3317 33.3'
    -
      - menu-3427
  /search-panel/: {  }
  /left-panel/: {  }
  /right-panel/: {  }
  /full-width-section-1/: {  }
  /main/:
    -
      - system-messages-7826
    -
      - system-content-8723
  /full-width-section-2/:
    -
      - position-module-4718
  /top-footer/: {  }
  /footer/: {  }
  /bottom-footer/:
    -
      - 'copyright-1257 72'
      - 'logo-5556 5'
      - 'custom-4473 23'
  /full-width-section-3/: {  }
structure:
  top-panel:
    type: section
    title: 'Top Panel'
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
  search-panel:
    type: section
    title: 'Search Panel'
    attributes:
      boxed: ''
  left-panel:
    type: section
    title: 'Left Panel'
    attributes:
      boxed: ''
  right-panel:
    type: section
    title: 'Right Panel'
    attributes:
      boxed: ''
  full-width-section-1:
    type: section
    title: 'Full Width Section 1'
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  full-width-section-2:
    type: section
    title: 'Full Width Section 2'
    attributes:
      boxed: '2'
      class: ''
  top-footer:
    type: section
    title: 'Top Footer'
    attributes:
      boxed: ''
      class: ''
  footer:
    attributes:
      boxed: ''
      class: bg-image
  bottom-footer:
    type: section
    title: 'Bottom Footer'
    attributes:
      boxed: ''
  full-width-section-3:
    type: section
    title: 'Full Width Section 3'
    attributes:
      boxed: ''
content:
  custom-3381:
    title: 'Custom HTML'
    attributes:
      html: '<h1 style="color:#fff;text-align:center;font-weight:500;letter-spacing:2px;margin:0;line-height:144px">Сайт на стадии разработки.Альфа тестирование произойдёт 24 Марта </h1>'
  jf_panel_buttons-3317:
    title: 'JF Panel Buttons'
    attributes:
      btns:
        -
          jf_btn_type: dropdown
          jf_p_html_open: '<i class="material-icons" style="font-size:20px">share</i>'
          jf_p_html_close: '<i class="material-icons" style="font-size:20px">share</i>'
          dr_list_1_text: Facebook
          dr_list_1_link_url: 'https://www.facebook.com/JoomForest'
          dr_list_1_link_target: blank
          dr_list_2_text: Twitter
          dr_list_2_link_url: 'https://twitter.com/#!/JoomForest'
          dr_list_2_link_target: blank
          dr_list_3_text: Google+
          dr_list_3_link_url: 'https://plus.google.com/+JoomForest/'
          dr_list_3_link_target: blank
          dr_list_4_text: Youtube
          dr_list_4_link_url: 'https://www.youtube.com/JoomForest'
          dr_list_4_link_target: blank
          dr_list_5_text: ''
          dr_list_5_link_url: ''
          dr_list_5_link_target: blank
          dr_list_6_text: ''
          dr_list_6_link_url: ''
          dr_list_6_link_target: blank
          dr_list_7_text: ''
          dr_list_7_link_url: ''
          dr_list_7_link_target: blank
          dr_list_8_text: ''
          dr_list_8_link_url: ''
          dr_list_8_link_target: blank
          dr_list_9_text: ''
          dr_list_9_link_url: ''
          dr_list_9_link_target: blank
          name: Dropdown
  menu-3427:
    attributes:
      menu: fdaf
      hoverExpand: '0'
  position-module-4718:
    title: 'Module Instance'
    attributes:
      module_id: '111'
      key: module-instance
  copyright-1257:
    attributes:
      owner: "SHEXP.<br>Education, Audiovisual and Culture Executive Agency\nCall for proposals EAC/A04/2015 - Jean Monnet Activities\nAgreement n. 2016 - 2594/001-001\nProject № 575018-EPP-1-2016-1-RU-EPPJMO-MODULE"
    block:
      extra:
        -
          data-animation: fadeInUp
        -
          data-animation-type: onview
  logo-5556:
    attributes:
      enabled: 0
      jf_logo_type: image
      url: 'https://www.joomforest.com'
      text: 'Premium Responsive Joomla Templates | JoomForest'
      image: 'gantry-media://joomforest.png'
      image_width: 120px
      image_height: 82px
    block:
      extra:
        -
          data-animation: fadeInUp
        -
          data-animation-type: onview
        -
          data-animation-delay: '0.2'
  custom-4473:
    title: 'Custom HTML'
    attributes:
      html: "<div data-foreground=\"dark\">\n<ul class=\"jf_social_icons hover_anim\" style=\"text-align:right;margin:18px 0\">\n\t<li class=\"facebook\"><a class=\"jf_waves_light_40 s\" href=\"http://www.facebook.com/JoomForest\" target=\"_blank\"><i class=\"fa fa-facebook default\"></i><i class=\"fa fa-facebook hover\"></i></a></li>\n\t<li class=\"twitter\"><a class=\"jf_waves_light_40 s\" href=\"http://twitter.com/#!/JoomForest\" target=\"_blank\"><i class=\"fa fa-twitter default\"></i><i class=\"fa fa-twitter hover\"></i></a></li>\n\t<li class=\"google\"><a class=\"jf_waves_light_40 s\" href=\"https://plus.google.com/+JoomForest/\" target=\"_blank\" title=\"+\"><i class=\"fa fa-google-plus default\"></i><i class=\"fa fa-google-plus hover\"></i></a></li>\n\t<li class=\"youtube\"><a class=\"jf_waves_light_40 s\" href=\"#\"><i class=\"fa fa-youtube-play default\"></i><i class=\"fa fa-youtube-play hover\"></i></a></li>\n</ul></div>"
    block:
      extra:
        -
          data-animation: fadeInUp
        -
          data-animation-type: onview
        -
          data-animation-delay: '0.4'
